name: CI

on:
  push:
    branches:
      - dev
      - main
    pull_request:
      - dev
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Instala dependências
        run: composer install --prefer-dist --no-interaction

      - name: Rodar qualidade do código
        run: composer quality